# Generated by Django 5.0.14 on 2026-02-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residentpage',
            old_name='short_description',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='residentpage',
            name='genre',
            field=models.TextField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='residentpage',
            name='more_info_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='residentpage',
            name='spotify_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='residentpage',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
