# Generated by Django 4.2.7 on 2023-11-08 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0002_alter_concertpage_ticket_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="concertpage",
            options={"ordering": ["concert_date"]},
        ),
    ]
