# Generated by Django 3.2.8 on 2021-10-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('font_awesome_icon', models.CharField(help_text='Zoek een icoontje op https://fontawesome.com/', max_length=50)),
            ],
        ),
    ]
