# Generated by Django 4.2.7 on 2023-11-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_sociallink"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailRecipients",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_form",
                    models.EmailField(default="jonas@mostaard.be", max_length=254),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
