# Generated by Django 3.2.8 on 2022-02-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='short_description',
            field=models.TextField(default='', max_length=150),
        ),
    ]
